version: '3.8'

services:
  loki:
    image: grafana/loki:2.7.1
    ports:
      - "${LOKI_PORT_HOST}:${LOKI_PORT_HOST}"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-wal:/wal
    user: "0"

  grafana:
    image: grafana/grafana:9.5.0
    ports:
      - "${GRAFANA_PORT_HOST}:${GRAFANA_PORT_HOST}"
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_HOST}:${APP_PORT_HOST}"
    env_file: .env

volumes:
  grafana-data:
  loki-wal:
