version: '3.8'

services:
  loki:
    image: grafana/loki:2.7.1
    ports:
      - "${LOKI_PORT_HOST}:${LOKI_PORT_CONTAINER}"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-wal:/wal
    user: "0"
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana:9.5.0
    ports:
      - "${GRAFANA_PORT_HOST}:${GRAFANA_PORT_CONTAINER}"
    env_file: .env
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - loki
    networks:
      - app-network

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=HumanFlowTaskManagerDB
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
    depends_on:
      - redis
      - loki
      - mongo
    networks:
      - app-network

volumes:
  grafana-data:
  loki-wal:
  redis-data:
  mongo-data:

networks:
  app-network:
    driver: bridge