# Use Node.js base image
FROM node:16-bullseye

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run make

# Set the command to run the application
CMD ["npm", "start"]
